services:
  pulse-frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - pulse-backend

  pulse-backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - pulse_db:/app/data

volumes:
  pulse_db:
